version: '3.1'

services:

  drupal:
    image: edwinkent/catshop
    ports:
      - 80:80
    volumes:
      - .:/app/web/profiles/custom/catshop
      - ./data/drupal:/app/web/sites
      - ./data/config:/app/config
    restart: always
    environment:
      WEB_DOCUMENT_ROOT: /app/web

  db:
    image: mysql:5.7.21
    ports:
      - "3388:3306"
    volumes:
      - "./data/mysql/data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123